version: '3.4'
services:
  client:
    build: ./client
    ports:
      - 5173:5173
    container_name: linkedin-client
  server:
    container_name: linkedin-server
    build: ./server
    ports:
      - 3000:3000